// This file is auto-generated by ./bin/rails stimulus:manifest:update
// Run that command whenever you add a new controller or create them with
// ./bin/rails generate stimulus controllerName

import { application } from "./application"

import ClipboardController from "./clipboard_controller"
application.register("clipboard", ClipboardController)

import ConfettiController from "./confetti_controller"
application.register("confetti", ConfettiController)

import ConfirmController from "./confirm_controller"
application.register("confirm", ConfirmController)

import DirectUploadController from "./direct_upload_controller"
application.register("direct-upload", DirectUploadController)

import DragDropObserverController from "./drag_drop_observer_controller"
application.register("drag-drop-observer", DragDropObserverController)

import DropzoneController from "./dropzone_controller"
application.register("dropzone", DropzoneController)

import FormController from "./form_controller"
application.register("form", FormController)

import ModalController from "./modal_controller"
application.register("modal", ModalController)

import ModalLinkController from "./modal_link_controller"
application.register("modal-link", ModalLinkController)

import RichTextController from "./rich_text_controller"
application.register("rich-text", RichTextController)

import SelfDestructController from "./self_destruct_controller"
application.register("self-destruct", SelfDestructController)

import TrixButtonController from "./trix_button_controller"
application.register("trix-button", TrixButtonController)

import VideoPlayerController from "./video_player_controller"
application.register("video-player", VideoPlayerController)
