// This file is auto-generated by ./bin/rails stimulus:manifest:update
// Run that command whenever you add a new controller or create them with
// ./bin/rails generate stimulus controllerName

import { application } from "./application"

import ClipboardController from "./clipboard_controller"
application.register("clipboard", ClipboardController)

import ConfirmController from "./confirm_controller"
application.register("confirm", ConfirmController)

import FormController from "./form_controller"
application.register("form", FormController)

import ModalController from "./modal_controller"
application.register("modal", ModalController)

import ModalLinkController from "./modal_link_controller"
application.register("modal-link", ModalLinkController)

import PlausibleController from "./plausible_controller"
application.register("plausible", PlausibleController)

import RichTextController from "./rich_text_controller"
application.register("rich-text", RichTextController)

import SelfDestructController from "./self_destruct_controller"
application.register("self-destruct", SelfDestructController)

import TrixButtonController from "./trix_button_controller"
application.register("trix-button", TrixButtonController)
